version: "3.2"
services:
  book_store_nginx:
    container_name: book_store_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./application:/var/www/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - book_store_php
  book_store_php:
    container_name: book_store_php
    build: .
    image: php_mysqli
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./application:/var/www/html
      - ./conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    depends_on:
      - book_store_mysql
  book_store_mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: database
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: root_password

